site_name: Argonaut Documentation
repo_url: https://github.com/CI-CMG/argonaut
repo_name: Argonaut
site_author: Rudy Klucik
site_url: https://ci-cmg.github.io/argonaut-documentation/
site_description: Argonaut is for processing Argo GDAC datasets
theme:
  name: material
  font:
    # all google fonts are available
    text: Merriweather sans
    code: Red Hat Mono
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  icon:
    logo: fontawesome/solid/anchor
    repo: fontawesome/brands/github
#  logo: assets/logo.png
#  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

#plugins:
#  - git-revision-date-localized:
#      enable_creation_date: true

# https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
markdown_extensions:
  - attr_list

  # emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # code highlighting
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # fences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # admonitions
  - admonition
  - pymdownx.details

  # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@NOAASatellites
    - icon: simple/facebook
      link: https://www.facebook.com/NOAANCEI/
    - icon: simple/instagram
      link: https://www.instagram.com/noaa_aoml

copyright: <i>Cooperative Institute for Research in Environmental Sciences</i>, Marine Geology & Geophysics Developer Team

#nav:
#  - Introduction: index.md
#  - Cookbook: cookbook.md
#  - Getting started:
#      - getting-started/index.md
#      - Installation: getting-started/installation.md
#      - First steps: getting-started/first-steps.md
#      - Features: getting-started/features.md
#      - Getting help: getting-started/help.md
#  - Guides:
#      - guides/index.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn